### ISSUE TITLE
argument 1 has unexpected type 'sip.voidptr'

### ISSUE THREAD

**Issue by Gronkman** [FreeOpcUa/opcua-client-gui#11]
When trying to run the client I get the following error:argument 1 has unexpected type 'sip.voidptr'.
It seems to come from the following line in the code: self.restoreState(self.settings.value("main_window_state", b"")). 
Any ideas on a fix?

**Comment by oroulet** [comment]
Remove that line. Should do a new release

**Comment by Gronkman** [comment]
thank you that did the trick
