### ISSUE TITLE
ImportError: No module named uaclient

### ISSUE THREAD

**Issue by mitjafelicijan** [FreeOpcUa/opcua-client-gui#16]
I have installed gui client with sudo pip install opcua-client and I am getting this error. I have also installed freeopcua with pip.

Is there any way to get this working?

```
m@grunt » opcua-client
Traceback (most recent call last):
  File "/usr/local/bin/opcua-client", line 7, in <module>
    from uaclient.mainwindow import main
  File "/usr/local/lib/python2.7/dist-packages/uaclient/mainwindow.py", line 16, in <module>
    from uaclient.uaclient import UaClient
ImportError: No module named uaclient
```

**Comment by oroulet** [comment]
uaclient is part of opcu-client and freeopcua should be downloaded automatically, but I see that you are using python 2.7, I am really not sure the GUI works with python 2.7, did pip let you install it?

**Comment by johndzilva** [comment]
you should probably try installing the opcua-client using pip3 command install.... I think when you install with pip command, the uaclient.py import will not work. 
And make sure you have latest PyQt installed.

**Comment by dvucko** [comment]
I just want to confirm that installing with `pip3` resolves the original issue, at least on my system.

**Comment by WangAllen** [comment]
![image](https://user-images.githubusercontent.com/30387965/50391550-a57b2f00-0781-11e9-996b-ebd4cc954299.png)
what‘s wrong with ’opcua-client‘ transformed to python2？

**Comment by oroulet** [comment]
Something broken on you PC. But anyway this is supposed to be s python 3 application

**Comment by PorkPy** [comment]
Sorry, I'm late to the party but could this error be because you already have a python2 version installed?
You may need to 'pip uninstall opcua-client' first.
I'm also trying to install opcua-client but my error is:
 
![image](https://user-images.githubusercontent.com/35999620/53347668-7dd74d00-3911-11e9-8960-523eda2523fc.png)
I suspect I'm missing some dependancy??

**Comment by zerox1212** [comment]
Are you trying to run this on Windows?

**Comment by PorkPy** [comment]
No, Ubuntu 16.04. I don’t like the burgundy bash.

**Comment by Shide** [comment]
You should install `opcua` and `opcua-client` with default python command:

    python -m pip install --upgrade opcua

    python -m pip install --upgrade opcua-client
