### ISSUE TITLE
Issue that duplicates objects

### ISSUE THREAD

**Issue by aquari89** [FreeOpcUa/opcua-client-gui#19]
I am currently using GUI client for testing purposes.

During testing with the GUI client, I found one problem.
When testing with the example server of Unified Automation, there is a problem that objects are duplicated.
This should not happen when testing with PythonOpcUa Server.

I attached the picture of the problem here.
![image](https://cloud.githubusercontent.com/assets/26217074/25260448/33e4fbf0-2687-11e7-9d6d-487d7e370753.png)

From a functional point of view I have verified many things. By the way, how do you call method in GUI client?
Has it not been implemented yet?

**Comment by oroulet** [comment]
method call is not implemented. 
What do you do to make 2 instances of same node visible? Can you write a scenario?

**Comment by aquari89** [comment]
The above server is not my development.
Currently I am using the .Net Sample Server provided by Unified Automation.

(Reference : http://documentation.unified-automation.com/uasdkdotnet/2.5.4/html/L3ServerTutGSLess06.html)

**Comment by oroulet** [comment]
fixed in https://github.com/FreeOpcUa/opcua-widgets/commit/84609442f6dcd75ef320c2049781becaf77a4597
not released yet

**Comment by aquari89** [comment]
I applied the code you modified and checked freeopcua gui client tool.
It runs well.
![image](https://cloud.githubusercontent.com/assets/26217074/25363971/edd8d238-2999-11e7-9bfd-a22ac777fe9a.png)
