### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by freetom** [FreeOpcUa/opcua-client-gui#20]
I followed the instruction to install the software. Installed the dependencies like PyQt5. When I try to run it with `opcua-client` I just get a "segmentation fault".

System is Debian 8, testing. Attached valgrind output

[valgrind_log.txt](https://github.com/FreeOpcUa/opcua-client-gui/files/1049489/valgrind_log.txt)

**Comment by oroulet** [comment]
Hi, opcua-client is python application. A segfault is nearly never a python
programming error.  There is something broken in your system. Does any
other qt5 application work? Any pyqt5 application?

**Comment by freetom** [comment]
I just tested qupzilla, from [here](https://wiki.manjaro.org/index.php?title=List_of_Qt_Applications). It uses Qt5 and seems to work..

**Comment by MattsSe** [comment]
It seems that the newest version of pyqt5 (5.8.2) is incompatible.
I downgraded to 5.8.1.1 and everything seems to work again 
`pip install -Iv pyqt5==5.8.1.1` fixed it for me

**Comment by oroulet** [comment]
what issue do you get? the API should be stable so it sounds like a qt bug

**Comment by MattsSe** [comment]
Just `[1]    1871 segmentation fault  opcua-client` on the console

**Comment by oroulet** [comment]
ok this is probably somehting on the distrib. library version osv..

**Comment by freetom** [comment]
Using Python2 was probably my issue. With Python3 it works fine
