### ISSUE TITLE
How to delete and restore settings.

### ISSUE THREAD

**Issue by crenwick** [FreeOpcUa/opcua-client-gui#23]
My window settings are in a bugged state, and I only have access to the tree window. How do I reset these settings to default?

I tried uninstalling/reinstalling opcua-client and pyqt5, but it still loads with the same window settings (macOS).

**Comment by crenwick** [comment]
Edited my local source code and commented out the lines:
```python3
        if data:
            self.restoreState(data)
```
Then, opened and closed the program. Then reinstalled the program (to delete my local changes).

**Comment by oroulet** [comment]
You need to find config files and delete/edit it Under .
Config/FreeOpcUa/UaClient.config or something similar in Linux
