### ISSUE TITLE
TypeError: QMainWindow.restoreState(QByteArray, int version=0): argument 1 has unexpected type 'unicode'

### ISSUE THREAD

**Issue by koppi** [FreeOpcUa/opcua-client-gui#3]
On Ubuntu 16.04 I ran:
```bash
~❯ freeopcua-client
Traceback (most recent call last):
  File "/usr/local/bin/freeopcua-client", line 9, in <module>
    load_entry_point('freeopcua-client==0.4.5', 'console_scripts', 'freeopcua-client')()
  File "/usr/local/lib/python2.7/dist-packages/freeopcuaclient/mainwindow.py", line 462, in main
    client = Window()
  File "/usr/local/lib/python2.7/dist-packages/freeopcuaclient/mainwindow.py", line 326, in __init__
    self.restoreState(self.settings.value("main_window_state", b""))
TypeError: QMainWindow.restoreState(QByteArray, int version=0): argument 1 has unexpected type 'unicode'
```
Any ideas, what could cause this?

**Comment by oroulet** [comment]
This is the settings stuff. Will have a look

**Comment by fville** [comment]
I resolved the error with this change:
`self.restoreState(self.settings.value("main_window_state", b"", type='QByteArray'))`

**Comment by koppi** [comment]
Thank's @fville . With the above change I now can open the gui. @oroulet please merge the change and close this issue.

**Comment by oroulet** [comment]
@fville thanks but please report issues and even better create pull request!

**Comment by oroulet** [comment]
Sorry I had forgotten that bug. Feel free to ping me. Github is not very good at reminding bugs

**Comment by fville** [comment]
I created a pull request  (too late apparently): #5 
This is a blind fix because I can't run the opcua-client-gui
I get this:
`Traceback (most recent call last):
  File "freeopcuaclient/mainwindow.py", line 12, in <module>
    from opcua.common.ua_utils import string_to_variant, variant_to_string, val_to_string
ImportError: No module named ua_utils
`

**Comment by oroulet** [comment]
sorry for that. the GUI is jsut now depending on a branch og python-opcua which I could not merge because of dependency to datetutil. Will try to fix this asap

**Comment by oroulet** [comment]
I just merged the PR in python-opcua, if now use python-opcua from master you will be able to run opcua-client-gui from master too. I fixed many things lately so information is now much better presented for humans and you can write values

**Comment by koppi** [comment]
Thank's for opcua-client-gui @oroulet . Closing this issue as resolved.
