### ISSUE TITLE
How to build the project in windows?

### ISSUE THREAD

**Issue by liuyazui** [FreeOpcUa/opcua-client-gui#95]

**Comment by schroeder-** [comment]
From the readme

Windows:
Install winpython https://winpython.github.io/ , install the version including pyqt5!
Use pip to install opcua-client: pip install opcua-client
Run via the script pip created: YOUR_INSTALL_PATH\Python\Python35\Scripts\opcua-client.exe
To update to the latest release run: pip install opcua-client --upgrade

But you can just try to this line:
pip install opcua-client

**Comment by liuyazui** [comment]
I mean how to build from the source file. When I run `python3 app.py`, doesn't show th gui window.

**Comment by schroeder-** [comment]
python setup.py install
